{% set version = "2.0.1" %}

package:
  name: mi-programoptions
  version: {{ version }}

source:
  url: https://github.com/metno/mi-programoptions/archive/v{{ version }}.tar.gz
  sha256: d662fb0d0a911538f92366353db21b9d49d8abc46bc938ea79fa5dfba9347b06
  folder: source

build:
  number: 1
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make         # [not win]
    - ninja        # [win]
  host:
    - mi-cpptest

test:
  commands:
    - test -f $PREFIX/include/mi_programoptions.h  # [unix]
    - test -f $PREFIX/lib/libmi-programoptions$SHLIB_EXT  # [unix]

about:
  home: https://github.com/metno/mi-programoptions
  license: GPL-2.0-or-later
  license_file: source/LICENSE.txt
  summary: MET Norway program options library

extra:
  recipe-maintainers:
    - alexander-buerger-met-no
    - audunc
    - heikoklein
